spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable-ui?serverTimezone=GMT
    username: flowable-ui
    password: flowable-ui
    local-cache-scope: statement

flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  #  将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  #  database-schema-update设置为true，当数据库中表结构不存在时，会自动创建表结构
  database-schema-update: true

server:
  port: 8888